# Generated by Django 6.0.1 on 2026-03-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserUpload',
        ),
    ]
